### ISSUE TITLE
Fatal: Layer PAD is not supported

### ISSUE THREAD

**Issue by mushroom-x** [AIWintermuteAI/transfer_learning_sipeed#1]
Follow the tutorial [Image Recogntion With Sipeed MaiX and Arduino IDE/Micropython](https://www.instructables.com/id/Transfer-Learning-With-Sipeed-MaiX-and-Arduino-IDE/) , 
that error occur:
```bash
$ ./tflite2kmodel.sh xo_model.tflite
uasge: ./tflite2kmodel.sh xxx.tflite
Fatal: Layer PAD is not supported
```

**Comment by AIWintermuteAI** [comment]
Hi! There are two sorts of problems that can cause this error:
1) You are using an outdated version of nncase. Developers added support for PAD  layer in RC4.
2) The padding size is wrong in Mobilenet script. 
![Capture](https://user-images.githubusercontent.com/32562299/60693264-42c2d700-9f0c-11e9-88b1-08ed8a599a2d.PNG)
![Capture1](https://user-images.githubusercontent.com/32562299/60693268-45253100-9f0c-11e9-93f7-0187035f6ae9.PNG)
Tell me if it solved your problem!
